name: "Chilean Rut CI"

on:
  pull_request:
    branches: ['master']
    paths:
      - '**.php'
      - 'composer.json'
      - '.github/workflows/ci.yml'
      - '.github/workflows/php.yml'
  push:
    branches: ['master']
    paths:
      - '**.php'
      - 'composer.json'
      - '.github/workflows/ci.yml'
      - '.github/workflows/php.yml'
jobs:
  ci:
    name: 'CI'
    uses: ./.github/workflows/php.yml
    with:
      php-version: 8.2
      composer-cmd: install --ansi --no-interaction --no-progress --no-suggest --prefer-dist
    secrets: inherit